# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Willows Montessori Nursery
email: willowsmontessorinursery@gmail.com
description: >
  Willows Montessori Nursery is a small, friendly, child centred Nursery set in the beautiful surroundings of Old Ryton Village, Gateshead.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://willowsmontessorinursery.net" # the base hostname & protocol for your site
host: 0.0.0.0

# Build settings
markdown: kramdown
exclude: ['source', Vagrantfile, Gemfile, Gemfile.lock, vhost.conf, README.md, provision.sh]

collections:
  parents:
    output: true
  policies:
    output: true
  learning_and_development:
    output: true
  willows:
    output: true
  rooms:
    output: true
