# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Willows Montessori Nursery
email: willowsmontessorinursery@gmail.com
description: >
  Willows Montessori Nursery is a small, friendly, child centred Nursery set in the beautiful surroundings of Old Ryton Village, Gateshead.
baseurl: "/willows2016/" # the subpath of your site, e.g. /blog
# url: "http://willowsmontessorinursery.net" # the base hostname & protocol for your site
host: 0.0.0.0
# permalink: pretty

# Build settings
markdown: kramdown
exclude: ['source', Vagrantfile, Gemfile, Gemfile.lock, vhost.conf, README.md, provision.sh]

collections:
  parents:
    output: true
    permalink: /parents/:path
  policies:
    output: true
    permalink: /policies/:path
  learning_and_development:
    output: true
    permalink: /learning-and-development/:path
  willows:
    output: true
    permalink: /willows/:path
  # rooms:
  #   output: true
  #   permanlink: /rooms/:path

defaults:
  -
    scope:
      path: ""
      type: 'parents'
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: 'policies'
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: 'learning_and_development'
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: 'willows'
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: 'rooms'
    values:
      layout: "page"
