backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "images"
collections:
  - name: "gallery - badger room"
    label: "Badger Room Images"
    folder: "images/badger"
    create: true
    slug: "{{ slug }}"
    fields:
      - {label: "Image", name: "image", widget: "image"}
  - name: "about-us"
    label: "About Us"
    folder: "_about-us"
    create: true
    slug: "{{ slug }}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Gallery", name: "gallery", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "philosophy"
    label: "Philosophy"
    folder: "_philosophy"
    create: true
    slug: ""
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Gallery", name: "gallery", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "testimonials"
    label: "Testimonials"
    folder: "_testimonials"
    create: true
    slug: ""
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Gallery", name: "gallery", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "forest-school"
    label: "Forest School"
    folder: "_forest-school"
    create: true
    slug: ""
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Gallery", name: "gallery", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"} 
  - name: "policies"
    label: "policies"
    folder: "_policies"
    create: true
    slug: ""
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Gallery", name: "gallery", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "sessions"
    label: "Sessions"
    folder: "_sessions"
    create: true
    slug: ""
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Gallery", name: "gallery", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}