backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "images"
collections:
  - name: "about-us"
    label: "About Us"
    folder: "_about-us"
    create: true
    slug: ""
    fields:
      - {}
  - name: "philosophy"
    label: "Philosophy"
    folder: "_philosophy"
    create: true
    slug: ""
    fields:
      - {}
  - name: "testimonials"
    label: "Testimonials"
    folder: "_testimonials"
    create: true
    slug: ""
    fields:
      - {}
  - name: "forest-school"
    label: "Forest School"
    folder: "_forest-school"
    create: true
    slug: ""
    fields:
      - {} 
  - name: "policies"
    label: "policies"
    folder: "_policies"
    create: true
    slug: ""
    fields:
      - {}
  - name: "sessions"
    label: "Sessions"
    folder: "_sessions"
    create: true
    slug: ""
    fields:
      - {}